name: mobile_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.2.3
  import_sorter: ^4.6.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.0.0
  json_annotation: ^4.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  melos: ^6.1.0
  build_runner: ^2.3.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  assets:
    - assets/data/

  uses-material-design: true

